const keywords = [
  "yo",
  "hello",
  "bonjour",
  "hi",
  "hey",
  "salut",
  "bonsoir",
  "good morning",
  "good afternoon",
  "good evening",
  "je suis",
  "je m'appelle",
  "je viens de",
  "je suis développeur",
  "je suis graphiste",
  "bonjour à tous",
  "salut tout le monde",
  "coucou",
  "je me présente",
  "mon nom est",
  "je m'appelle",
  "je vis à",
  "je travaille comme",
  "je travaille en tant que",
  "je suis originaire de",
  "heureux de rejoindre",
  "ravie de rejoindre",
  "impatient de",
  "hâte de",
  "je suis passionné par",
  "je suis ici pour",
  "je rejoins cette communauté",
  "je suis ravi de",
  "je suis nouveau ici",
  "je suis freelance",
  "je suis ingénieur",
  "je suis développeuse",
  "je suis designer",
  "je suis étudiant",
  "je suis chercheur",
  "je suis entrepreneur",
  "je suis analyste",
  "je suis manager",
  "je suis architecte",
  "je suis consultant",
  "je suis formateur",
  "je suis professeur",
  "je suis coach",
  "je suis data scientist",
  "je suis chef de projet",
  "je suis technicien",
  "je suis développeur full-stack",
  "je suis développeur backend",
  "je suis développeur frontend",
  "je suis expert en",
  "je suis spécialiste en",
  "je suis débutant",
  "je suis intéressé par",
  "le code",
  "le développement web",
  "le développement mobile",
  "la blockchain",
  "le no-code",
  "wordpress",
  "webflow",
  "l'IA",
  "la data science",
  "je débute",
  "je veux apprendre",
];
